### ISSUE TITLE
Delayed video start and fast forward / backward

### ISSUE THREAD

**Issue by CoRoe** [gerbera/gerbera#2711]
When I press the PLAY button of the TV set's remote control, actual playback starts only after ~ 10 seconds. When pressing FFWD or FBWD, playback is delayed for many seconds.

Gerbera 1.11.0, sqlite
Linux Mint, kernel 5.4.0-126-generic, Lenovo ideapad 330S, 1 TB SSD
Client: Panasonic TX49 smart TV

**Comment by KarlStraussberger** [comment]
There many things that can cause a delay.

First of all devices tend to cache part of the stream. You can try turning on logging (--debug) in gerbera to see when requests are handled and how often the client repeats request. Also monitor the cpu load and the network. Sometime the devices need time to get the audio stream in sync.

Maybe you can investigate a bit further to identify an issue on either side.

**Comment by CoRoe** [comment]
Thanks for your quick reaction!

[gerbera.log](https://github.com/gerbera/gerbera/files/9674885/gerbera.log)
[start-video-ffwd.zip](https://github.com/gerbera/gerbera/files/9674904/start-video-ffwd.zip)

System load is low, none of the 8 cores goes above 25%.

I noticed that Gerbera's send q is very long:
```
cro@klapp:~$ ss 'sport 49152'
Netid State Recv-Q Send-Q    Local Address:Port      Peer Address:Port  Process 
tcp   ESTAB 0      2930752  192.168.178.20:49152   192.168.178.24:42192
```         
Don't know if this is normal.

Gerbera used to work fine on my system, I cannot say exactly when the problem started. Some weeks ago, I replaced the HDD with an SSD; possibly that broke Gerbera (although I cannot imagine why).

**Comment by KarlStraussberger** [comment]
I just checked your log and found an interesting pattern: there are several gaps of 10 secs. This points to the client itself. Any recent fw updates on that side?

**Comment by CoRoe** [comment]
Interesting root cause: Gerbera performs from time to time a reverse DNS lookup of the rendering device:

42513 17:41:05.849798 socket(AF_INET, SOCK_DGRAM|SOCK_CLOEXEC|SOCK_NONBLOCK, IPPROTO_IP) = 18
42513 17:41:05.849965 setsockopt(18, SOL_IP, IP_RECVERR, [1], 4) = 0
42513 17:41:05.850142 connect(18, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("127.0.0.53")}, 16) = 0
42513 17:41:05.850348 poll([{fd=18, events=POLLOUT}], 1, 0) = 1 ([{fd=18, revents=POLLOUT}])
42513 17:41:05.850519 sendto(18, "$\327\1 \0\1\0\0\0\0\0\1\0017\0011\003168\003192\7in-addr"..., 53, MSG_NOSIGNAL, NULL, 0) = 53
42513 17:41:05.850866 poll([{fd=18, events=POLLIN}], 1, 5000 <unfinished ...>
42501 17:41:09.184255 <... futex resumed>) = -1 ETIMEDOUT (Die Wartezeit für die Verbindung ist abgelaufen)
42501 17:41:09.184691 futex(0x559baa1ebb60, FUTEX_WAKE_PRIVATE, 1) = 0
42501 17:41:09.185289 futex(0x559baa1ebbb4, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, {tv_sec=1665675674, tv_nsec=184000000}, FUTEX_BITSET_MATCH_ANY <unfinished ...>
42499 17:41:10.212367 <... futex resumed>) = -1 ETIMEDOUT (Die Wartezeit für die Verbindung ist abgelaufen)
42499 17:41:10.212747 futex(0x559baa1ebb60, FUTEX_WAKE_PRIVATE, 1) = 0
42499 17:41:10.213184 futex(0x559baa1ebbb4, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, {tv_sec=1665675675, tv_nsec=212000000}, FUTEX_BITSET_MATCH_ANY <unfinished ...>
42502 17:41:10.213345 <... futex resumed>) = -1 ETIMEDOUT (Die Wartezeit für die Verbindung ist abgelaufen)
42502 17:41:10.213646 futex(0x559baa1ebea0, FUTEX_WAKE_PRIVATE, 1) = 0
42502 17:41:10.214182 futex(0x559baa1ebef4, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, {tv_sec=1665675675, tv_nsec=213000000}, FUTEX_BITSET_MATCH_ANY <unfinished ...>
42517 17:41:10.842274 <... futex resumed>) = -1 ETIMEDOUT (Die Wartezeit für die Verbindung ist abgelaufen)
42517 17:41:10.842632 futex(0x559baa1ec160, FUTEX_WAKE_PRIVATE, 1) = 0
42517 17:41:10.843057 madvise(0x7f2ad07f9000, 8368128, MADV_DONTNEED) = 0
42517 17:41:10.843500 exit(0)           = ?

Gerbera sets a time-put of 5 seconds, but the systemd-resolved replies only later with a 'not found' error message. This blocking DNS query delays all responses to HTTP GET /content requests.

Work-around: Add an entry to /etc/hosts so that the DNS lookup succeeds.

**Comment by KarlStraussberger** [comment]
Thanks for your investigation which is very helpful.
The request is used to fill in the client's name in the web UI. Also there are two debug messages that access that method. Maybe we can add some caching so there is only one call while gerbera is running.

**Comment by KarlStraussberger** [comment]
Can you try #2719

**Comment by CoRoe** [comment]
I tried to build Gerbera from source as described in 'Build On Ubuntu 18.04' but keep failing:

cro@klapp:~/src/gerbera/build$ make
[  1%] Building CXX object CMakeFiles/libgerbera.dir/src/action_request.cc.o
In file included from /home/cro/src/gerbera/gerbera/src/action_request.cc:32:
In file included from /home/cro/src/gerbera/gerbera/src/action_request.h:40:
In file included from /home/cro/src/gerbera/gerbera/src/common.h:36:
In file included from /home/cro/src/gerbera/gerbera/src/util/logger.h:36:
In file included from /usr/local/include/spdlog/spdlog.h:14:
/usr/local/include/spdlog/logger.h:375:13: error: no matching function for call to 'vformat_to'
            fmt::detail::vformat_to(buf, fmt, fmt::make_format_args(std::forward<Args>(args)...));
            ^~~~~~~~~~~~~~~~~~~~~~~

**Comment by KarlStraussberger** [comment]
It seems that this is once again outdated. I recommend running `scripts/debian/build-dep.sh`. It's used in our test. You may even call it with `HEAD` so it builds most libraries from  recent sources.

**Comment by CoRoe** [comment]
scripts/debian/build-dep.sh succeeded.

The problem is solved, no more delays.
