### ISSUE TITLE
Git master fail to build with pupnp 1.12

### ISSUE THREAD

**Issue by marillat** [gerbera/gerbera#682]
Hi,

Under debian unstable amd64 architecture.
```
[ 98%] Linking CXX executable gerbera
/usr/bin/cmake -E cmake_link_script CMakeFiles/gerbera.dir/link.txt --verbose=1
/usr/lib/ccache/c++  -g -O2 -fdebug-prefix-map=/src/gerbera-1.4.0+20200216.e1b880cc=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall  -Wl,-z,relro CMakeFiles/gerbera.dir/src/main.cc.o  -o gerbera  liblibgerbera.a -lpthread -latomic -lc /usr/lib/x86_64-linux-gnu/libuuid.so /usr/lib/x86_64-linux-gnu/libupnp.so /usr/lib/x86_64-linux-gnu/libixml.so -lupnp -lixml /usr/lib/x86_64-linux-gnu/libfmt.a /usr/lib/x86_64-linux-gnu/libspdlog.so.1.5.0 /usr/lib/x86_64-linux-gnu/libpugixml.so /usr/lib/x86_64-linux-gnu/libsqlite3.so /usr/lib/x86_64-linux-gnu/libnsl.so /usr/lib/x86_64-linux-gnu/libduktape.so /usr/lib/x86_64-linux-gnu/libmysqlclient_r.so -lcurl -L/usr/lib/x86_64-linux-gnu -ltag /usr/lib/x86_64-linux-gnu/libmagic.so -lavformat -lavutil /usr/lib/x86_64-linux-gnu/libffmpegthumbnailer.so /usr/lib/x86_64-linux-gnu/libexif.so /usr/lib/x86_64-linux-gnu/libexiv2.so /usr/lib/x86_64-linux-gnu/libebml.so -lebml /usr/lib/x86_64-linux-gnu/libmatroska.so -lmatroska /usr/lib/x86_64-linux-gnu/libz.so -lpthread 
/usr/bin/ld: liblibgerbera.a(headers.cc.o): in function `Headers::writeHeaders(s_UpnpFileInfo*) const':
./obj-x86_64-linux-gnu/./src/util/headers.cc:82: undefined reference to `UpnpListEnd(UpnpListHead*)'
/usr/bin/ld: ./obj-x86_64-linux-gnu/./src/util/headers.cc:82: undefined reference to `UpnpListInsert(UpnpListHead*, UpnpListHead*, UpnpListHead*)'
collect2: error: ld returned 1 exit status
```

**Comment by whyman** [comment]
It should build, can you post the cmake output?

**Comment by marillat** [comment]
It is the cmake output. Maybe do you want the complete build log ?

```
objdump -R /usr/lib/x86_64-linux-gnu/libupnp.so | grep UpnpListEnd
000000000003b848 R_X86_64_JUMP_SLOT  UpnpListEnd@@Base```

```$ dpkg -S /usr/lib/x86_64-linux-gnu/libupnp.so
libupnp-dev:amd64: /usr/lib/x86_64-linux-gnu/libupnp.so```

```$ dpkg -s libupnp-dev| grep Version:
Version: 1:1.12.0-dmo2```

**Comment by marillat** [comment]
Complet log file

https://gist.github.com/marillat/df64f8ea5ee67ad7b0880d2101885fac

**Comment by whyman** [comment]
Ah, okay, of course, you are correct!

You will need to [backport my patch](https://github.com/pupnp/pupnp/pull/160) from upstream pupnp to get it to build with C++.

**Comment by marillat** [comment]
Thanks build fine now.

**Comment by whyman** [comment]
No problem and thanks for your work!
