### ISSUE TITLE
gerbera 1.4.0 does not compile with GCC 9.3.0

### ISSUE THREAD

**Issue by neheb** [gerbera/gerbera#794]
Log:

```
src/main.cc: In function 'int main(int, char**, char**)':
src/main.cc:244:32: error: conversion from 'std::optional<std::__cxx11::basic_string<char> >' to non-scalar type 'zmm::String' requested
  244 |         String configFile_ = _(config_file);
      |                                ^
src/main.cc:245:26: error: conversion from 'std::optional<std::__cxx11::basic_string<char> >' to non-scalar type 'zmm::String' requested
  245 |         String home_ = _(home);
      |                          ^
src/main.cc:246:29: error: conversion from 'std::optional<std::__cxx11::basic_string<char> >' to non-scalar type 'zmm::String' requested
  246 |         String confdir_ = _(confdir);
      |                             ^
src/main.cc:247:28: error: conversion from 'std::optional<std::__cxx11::basic_string<char> >' to non-scalar type 'zmm::String' requested
  247 |         String prefix_ = _(prefix);
      |                            ^
src/main.cc:248:27: error: conversion from 'std::optional<std::__cxx11::basic_string<char> >' to non-scalar type 'zmm::String' requested
  248 |         String magic_ = _(magic);
      |                           ^
src/main.cc:249:24: error: conversion from 'std::optional<std::__cxx11::basic_string<char> >' to non-scalar type 'zmm::String' requested
  249 |         String ip_ = _(ip);
      |                        ^
src/main.cc:250:31: error: conversion from 'std::optional<std::__cxx11::basic_string<char> >' to non-scalar type 'zmm::String' requested
  250 |         String interface_ = _(interface);
      |                               ^
```

I understand that zmm is gone with https://github.com/gerbera/gerbera/issues/567 but this is still an issue with the release version.

**Comment by whyman** [comment]
Try a newer clang/libc++

**Comment by neheb** [comment]
This is version 9.0.1. The latest stable version.

**Comment by neheb** [comment]
Turns out this isn't even with libcxx... It's with GCC's libstdcpp.

GCC 9.3.0

**Comment by neheb** [comment]
tested GCC8 and 7. Same issue.

**Comment by neheb** [comment]
I'm going to close this. This is a git version of glibc. I assume they will fix this eventually.
