### ISSUE TITLE
Build failure with pupnp 1.8.5

### ISSUE THREAD

**Issue by ffontaine** [gerbera/gerbera#517]
Gerbera fails to build with pupnp 1.8.5 because UpnpFileInfo_set_ExtraHeaders has been removed:
```
[ 24%] Building CXX object CMakeFiles/libgerbera.dir/src/layout/fallback_layout.cc.o
/data/buildroot/buildroot-test/instance-0/output/build/gerbera-1.3.2/src/handler/headers.cc: In member function 'const void Headers::writeHeaders(UpnpFileInfo*)':
/data/buildroot/buildroot-test/instance-0/output/build/gerbera-1.3.2/src/handler/headers.cc:76:5: error: 'UpnpFileInfo_set_ExtraHeaders' was not declared in this scope
     UpnpFileInfo_set_ExtraHeaders(fileInfo, ixmlCloneDOMString(result.c_str()));
```

**Comment by whyman** [comment]
I thought that patch wasn't supposed to be in 1.8? and thats 1.10 was for? Or am I missing something?

**Comment by joerg-krause** [comment]
The incompatibility was introduced in https://github.com/mrjimenez/pupnp/commit/ef9c4e046e0906d28795ebcbef26d2549cde7c03.

**Comment by marillat** [comment]
gerbera also doesn't builld with upnp 1.10
If I understand 1.10 is the latest stable version.

**Comment by ffontaine** [comment]
Do you plan on fixing this issue any time soon? We have bumped the pupnp release in buildroot and we'll release our next version at the end of November but we can revert the bump if needed.

**Comment by whyman** [comment]
Well as I mentioned, I thought this would not be a problem until 1.10 was widely adopted

I had a quick look and to be honest the new API is confusing me, so, if anyone can give an example of how to add an extra header with the new API it would be appreciated....

**Comment by ffontaine** [comment]
Perhaps @mrjimenez can help as I didn't play with this new feature however I thought that this new design was added in 1.8.x especially for gerbera (through https://github.com/mrjimenez/pupnp/pull/98). Actually, 1.8.5 was released following the requests of gerbera users in https://github.com/mrjimenez/pupnp/issues/109

**Comment by marillat** [comment]
For me gerbera 1.3.4 doesn't build with upnp 1.10.0 Debian unstable amd64
```
[  1%] Building CXX object CMakeFiles/libgerbera.dir/src/server.cc.o
c++  -DATRAILERS -DHAVE_AVSTREAM_CODECPAR -DHAVE_CURL -DHAVE_EXIV2 -DHAVE_FFMPEG -DHAVE_FFMPEGTHUMBNAILER -DHAVE_INOTIFY -DHAVE_JS -DHAVE_LIBEXIF -DHAVE_MAGIC -DHAVE_MYSQL -DHAVE_NL_LANGINFO -DHAVE_SETLOCALE -DHAVE_SQLITE3 -DHAVE_TAGLIB -DONLINE_SERVICES -DPACKAGE_DATADIR=\"/usr/share/gerbera\" -DPACKAGE_NAME=\"Gerbera\" -DSOPCAST -DTOMBDEBUG -DUPNP_HAS_EXTRA_HEADERS_LIST -DVERSION=\"1.3.4\" -D__FILENAME__=\"src/server.cc\" -I/src/gerbera-1.3.4/src -I/usr/include/upnp -I/usr/include/mysql -I/usr/include/libexif -I/usr/include/exiv2  -g -O2 -fdebug-prefix-map=/src/gerbera-1.3.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall   -std=c++17 -o CMakeFiles/libgerbera.dir/src/server.cc.o -c /src/gerbera-1.3.4/src/server.cc
/src/gerbera-1.3.4/src/server.cc: In member function ‘int Server::registerVirtualDirCallbacks()’:
/src/gerbera-1.3.4/src/server.cc:468:20: error: invalid user-defined conversion from ‘Server::registerVirtualDirCallbacks()::<lambda(const char*, UpnpFileInfo*, const void*)>’ to ‘VDCallback_GetInfo’ {aka ‘int (*)(const char*, s_UpnpFileInfo*, const void*, const void**)’} [-fpermissive]
  468 |         return 0; });
      |                    ^
/src/gerbera-1.3.4/src/server.cc:455:50: note: candidate is: ‘constexpr Server::registerVirtualDirCallbacks()::<lambda(const char*, UpnpFileInfo*, const void*)>::operator int (*)(const char*, UpnpFileInfo*, const void*)() const’ <near match>
  455 |     int ret = UpnpVirtualDir_set_GetInfoCallback([](IN const char* filename, OUT UpnpFileInfo* info, const void* cookie) -> int {
      |                                                  ^
/src/gerbera-1.3.4/src/server.cc:455:50: note:   no known conversion from ‘int (*)(const char*, UpnpFileInfo*, const void*)’ {aka ‘int (*)(const char*, s_UpnpFileInfo*, const void*)’} to ‘VDCallback_GetInfo’ {aka ‘int (*)(const char*, s_UpnpFileInfo*, const void*, const void**)’}
In file included from /src/gerbera-1.3.4/src/io_handler.h:35,
                 from /src/gerbera-1.3.4/src/tools.h:42,
                 from /src/gerbera-1.3.4/src/timer.h:36,
                 from /src/gerbera-1.3.4/src/autoscan.h:36,
                 from /src/gerbera-1.3.4/src/content_manager.h:39,
                 from /src/gerbera-1.3.4/src/server.cc:41:
/usr/include/upnp/upnp.h:2591:71: note:   initializing argument 1 of ‘int UpnpVirtualDir_set_GetInfoCallback(VDCallback_GetInfo)’
 2591 | EXPORT_SPEC int UpnpVirtualDir_set_GetInfoCallback(VDCallback_GetInfo callback);
      |                                                    ~~~~~~~~~~~~~~~~~~~^~~~~~~~
/src/gerbera-1.3.4/src/server.cc:491:6: error: invalid user-defined conversion from ‘Server::registerVirtualDirCallbacks()::<lambda(const char*, UpnpOpenFileMode, const void*)>’ to ‘VDCallback_Open’ {aka ‘void* (*)(const char*, UpnpOpenFileMode, const void*, const void*)’} [-fpermissive]
  491 |     });
      |      ^
/src/gerbera-1.3.4/src/server.cc:473:43: note: candidate is: ‘constexpr Server::registerVirtualDirCallbacks()::<lambda(const char*, UpnpOpenFileMode, const void*)>::operator void* (*)(const char*, UpnpOpenFileMode, const void*)() const’ <near match>
  473 |     ret = UpnpVirtualDir_set_OpenCallback([](IN const char* filename, IN enum UpnpOpenFileMode mode, IN const void* cookie) -> UpnpWebFileHandle {
      |                                           ^
/src/gerbera-1.3.4/src/server.cc:473:43: note:   no known conversion from ‘void* (*)(const char*, UpnpOpenFileMode, const void*)’ to ‘VDCallback_Open’ {aka ‘void* (*)(const char*, UpnpOpenFileMode, const void*, const void*)’}
In file included from /src/gerbera-1.3.4/src/io_handler.h:35,
                 from /src/gerbera-1.3.4/src/tools.h:42,
                 from /src/gerbera-1.3.4/src/timer.h:36,
                 from /src/gerbera-1.3.4/src/autoscan.h:36,
                 from /src/gerbera-1.3.4/src/content_manager.h:39,
                 from /src/gerbera-1.3.4/src/server.cc:41:
/usr/include/upnp/upnp.h:2615:65: note:   initializing argument 1 of ‘int UpnpVirtualDir_set_OpenCallback(VDCallback_Open)’
 2615 | EXPORT_SPEC int UpnpVirtualDir_set_OpenCallback(VDCallback_Open callback);
      |                                                 ~~~~~~~~~~~~~~~~^~~~~~~~
/src/gerbera-1.3.4/src/server.cc:503:6: error: invalid user-defined conversion from ‘Server::registerVirtualDirCallbacks()::<lambda(UpnpWebFileHandle, char*, size_t, const void*)>’ to ‘VDCallback_Read’ {aka ‘int (*)(void*, char*, long unsigned int, const void*, const void*)’} [-fpermissive]
  503 |     });
      |      ^
/src/gerbera-1.3.4/src/server.cc:496:43: note: candidate is: ‘constexpr Server::registerVirtualDirCallbacks()::<lambda(UpnpWebFileHandle, char*, size_t, const void*)>::operator int (*)(UpnpWebFileHandle, char*, size_t, const void*)() const’ <near match>
  496 |     ret = UpnpVirtualDir_set_ReadCallback([](IN UpnpWebFileHandle f, OUT char* buf, IN size_t length, IN const void* cookie) -> int {
      |                                           ^
/src/gerbera-1.3.4/src/server.cc:496:43: note:   no known conversion from ‘int (*)(UpnpWebFileHandle, char*, size_t, const void*)’ {aka ‘int (*)(void*, char*, long unsigned int, const void*)’} to ‘VDCallback_Read’ {aka ‘int (*)(void*, char*, long unsigned int, const void*, const void*)’}
In file included from /src/gerbera-1.3.4/src/io_handler.h:35,
                 from /src/gerbera-1.3.4/src/tools.h:42,
                 from /src/gerbera-1.3.4/src/timer.h:36,
                 from /src/gerbera-1.3.4/src/autoscan.h:36,
                 from /src/gerbera-1.3.4/src/content_manager.h:39,
                 from /src/gerbera-1.3.4/src/server.cc:41:
/usr/include/upnp/upnp.h:2640:65: note:   initializing argument 1 of ‘int UpnpVirtualDir_set_ReadCallback(VDCallback_Read)’
 2640 | EXPORT_SPEC int UpnpVirtualDir_set_ReadCallback(VDCallback_Read callback);
      |                                                 ~~~~~~~~~~~~~~~~^~~~~~~~
/src/gerbera-1.3.4/src/server.cc:511:6: error: invalid user-defined conversion from ‘Server::registerVirtualDirCallbacks()::<lambda(UpnpWebFileHandle, char*, size_t, const void*)>’ to ‘VDCallback_Write’ {aka ‘int (*)(void*, char*, long unsigned int, const void*, const void*)’} [-fpermissive]
  511 |     });
      |      ^
/src/gerbera-1.3.4/src/server.cc:508:44: note: candidate is: ‘constexpr Server::registerVirtualDirCallbacks()::<lambda(UpnpWebFileHandle, char*, size_t, const void*)>::operator int (*)(UpnpWebFileHandle, char*, size_t, const void*)() const’ <near match>
  508 |     ret = UpnpVirtualDir_set_WriteCallback([](IN UpnpWebFileHandle f, IN char* buf, IN size_t length, IN const void* cookie) -> int {
      |                                            ^
/src/gerbera-1.3.4/src/server.cc:508:44: note:   no known conversion from ‘int (*)(UpnpWebFileHandle, char*, size_t, const void*)’ {aka ‘int (*)(void*, char*, long unsigned int, const void*)’} to ‘VDCallback_Write’ {aka ‘int (*)(void*, char*, long unsigned int, const void*, const void*)’}
In file included from /src/gerbera-1.3.4/src/io_handler.h:35,
                 from /src/gerbera-1.3.4/src/tools.h:42,
                 from /src/gerbera-1.3.4/src/timer.h:36,
                 from /src/gerbera-1.3.4/src/autoscan.h:36,
                 from /src/gerbera-1.3.4/src/content_manager.h:39,
                 from /src/gerbera-1.3.4/src/server.cc:41:
/usr/include/upnp/upnp.h:2665:67: note:   initializing argument 1 of ‘int UpnpVirtualDir_set_WriteCallback(VDCallback_Write)’
 2665 | EXPORT_SPEC int UpnpVirtualDir_set_WriteCallback(VDCallback_Write callback);
      |                                                  ~~~~~~~~~~~~~~~~~^~~~~~~~
/src/gerbera-1.3.4/src/server.cc:528:6: error: invalid user-defined conversion from ‘Server::registerVirtualDirCallbacks()::<lambda(UpnpWebFileHandle, off_t, int, const void*)>’ to ‘VDCallback_Seek’ {aka ‘int (*)(void*, long int, int, const void*, const void*)’} [-fpermissive]
  528 |     });
      |      ^
/src/gerbera-1.3.4/src/server.cc:516:43: note: candidate is: ‘constexpr Server::registerVirtualDirCallbacks()::<lambda(UpnpWebFileHandle, off_t, int, const void*)>::operator int (*)(UpnpWebFileHandle, off_t, int, const void*)() const’ <near match>
  516 |     ret = UpnpVirtualDir_set_SeekCallback([](IN UpnpWebFileHandle f, IN off_t offset, IN int whence, IN const void* cookie) -> int {
      |                                           ^
/src/gerbera-1.3.4/src/server.cc:516:43: note:   no known conversion from ‘int (*)(UpnpWebFileHandle, off_t, int, const void*)’ {aka ‘int (*)(void*, long int, int, const void*)’} to ‘VDCallback_Seek’ {aka ‘int (*)(void*, long int, int, const void*, const void*)’}
In file included from /src/gerbera-1.3.4/src/io_handler.h:35,
                 from /src/gerbera-1.3.4/src/tools.h:42,
                 from /src/gerbera-1.3.4/src/timer.h:36,
                 from /src/gerbera-1.3.4/src/autoscan.h:36,
                 from /src/gerbera-1.3.4/src/content_manager.h:39,
                 from /src/gerbera-1.3.4/src/server.cc:41:
/usr/include/upnp/upnp.h:2695:65: note:   initializing argument 1 of ‘int UpnpVirtualDir_set_SeekCallback(VDCallback_Seek)’
 2695 | EXPORT_SPEC int UpnpVirtualDir_set_SeekCallback(VDCallback_Seek callback);
      |                                                 ~~~~~~~~~~~~~~~~^~~~~~~~
/src/gerbera-1.3.4/src/server.cc:545:6: error: invalid user-defined conversion from ‘Server::registerVirtualDirCallbacks()::<lambda(UpnpWebFileHandle, const void*)>’ to ‘VDCallback_Close’ {aka ‘int (*)(void*, const void*, const void*)’} [-fpermissive]
  545 |     });
      |      ^
/src/gerbera-1.3.4/src/server.cc:533:38: note: candidate is: ‘constexpr Server::registerVirtualDirCallbacks()::<lambda(UpnpWebFileHandle, const void*)>::operator int (*)(UpnpWebFileHandle, const void*)() const’ <near match>
  533 |     UpnpVirtualDir_set_CloseCallback([](IN UpnpWebFileHandle f, IN const void* cookie) -> int {
      |                                      ^
/src/gerbera-1.3.4/src/server.cc:533:38: note:   no known conversion from ‘int (*)(UpnpWebFileHandle, const void*)’ {aka ‘int (*)(void*, const void*)’} to ‘VDCallback_Close’ {aka ‘int (*)(void*, const void*, const void*)’}
In file included from /src/gerbera-1.3.4/src/io_handler.h:35,
                 from /src/gerbera-1.3.4/src/tools.h:42,
                 from /src/gerbera-1.3.4/src/timer.h:36,
                 from /src/gerbera-1.3.4/src/autoscan.h:36,
                 from /src/gerbera-1.3.4/src/content_manager.h:39,
                 from /src/gerbera-1.3.4/src/server.cc:41:
/usr/include/upnp/upnp.h:2716:67: note:   initializing argument 1 of ‘int UpnpVirtualDir_set_CloseCallback(VDCallback_Close)’
 2716 | EXPORT_SPEC int UpnpVirtualDir_set_CloseCallback(VDCallback_Close callback);
      |                                                  ~~~~~~~~~~~~~~~~~^~~~~~~~
make[2]: *** [CMakeFiles/libgerbera.dir/build.make:898: CMakeFiles/libgerbera.dir/src/server.cc.o] Error 1
make[2] : on quitte le répertoire « /src/gerbera-1.3.4/obj-x86_64-linux-gnu »
make[1]: *** [CMakeFiles/Makefile2:112: CMakeFiles/libgerbera.dir/all] Error 2
make[1] : on quitte le répertoire « /src/gerbera-1.3.4/obj-x86_64-linux-gnu »
make: *** [Makefile:133: all] Error 2
make : on quitte le répertoire « /src/gerbera-1.3.4/obj-x86_64-linux-gnu »
```

**Comment by whyman** [comment]
@marillat Thanks! Forgot about that API...  :man_facepalming: 

1.8.5 will work now, though

**Comment by ffontaine** [comment]
Indeed, it builds fine with 1.8.5, thanks.

**Comment by marillat** [comment]
@whyman I can expect support for 1.10.0 too ?

**Comment by whyman** [comment]
@marillat, yes

**Comment by marillat** [comment]
@whyman Thanks in advance.
