### ISSUE TITLE
1.9.1 release with (lib)inotify support fails to compile on FreeBSD 13

### ISSUE THREAD

**Issue by diizzyy** [gerbera/gerbera#1848]
```
FAILED: CMakeFiles/libgerbera.dir/src/content/autoscan_inotify.cc.o
/usr/bin/c++ -DATRAILERS -DBSD -DBSD_NATIVE_UUID -DFMT_SHARED -DGERBERA_VERSION=\"1.9.1\" -DHAVE_AVSTREAM_CODECPAR -DHAVE_CURL -DHAVE_EXIV2 -DHAVE_FFMPEG -DHAVE_INOTIFY -DHAVE_JS -DHAVE_MAGIC -DHAVE_NL_LANGINFO -DHAVE_SETLOCALE -DHAVE_TAGLIB -DONLINE_SERVICES -DSOPCAST -DSPDLOG_ACTIVE_LEVEL=SPDLOG_LEVEL_INFO -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -DSPDLOG_SHARED_LIB -DUSING_NPUPNP -D_LIBCPP_ENABLE_CXX17_REMOVED_AUTO_PTR -I/usr/ports/net/gerbera/work/gerbera-1.9.1/src -I/usr/local/include/npupnp -I/usr/local/include/exiv2 -O2 -pipe -march=ivybridge -DLIBICONV_PLUG -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing  -DLIBICONV_PLUG -isystem /usr/local/include -O2 -pipe -march=ivybridge -DLIBICONV_PLUG -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing  -DLIBICONV_PLUG -isystem /usr/local/include -Wall -pthread -std=c++17 -MD -MT CMakeFiles/libgerbera.dir/src/content/autoscan_inotify.cc.o -MF CMakeFiles/libgerbera.dir/src/content/autoscan_inotify.cc.o.d -o CMakeFiles/libgerbera.dir/src/content/autoscan_inotify.cc.o -c /usr/ports/net/gerbera/work/gerbera-1.9.1/src/content/autoscan_inotify.cc
/usr/ports/net/gerbera/work/gerbera-1.9.1/src/content/autoscan_inotify.cc:351:28: error: implicit instantiation of undefined template 'std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char>>'
        std::ostringstream buf;
                           ^
/usr/include/c++/v1/iosfwd:136:32: note: template is declared here
    class _LIBCPP_TEMPLATE_VIS basic_ostringstream;
                               ^
1 error generated.
```
FreeBSD 13.0-STABLE #0 stable/13-n246086-a20c597c6d7 (amd64)
https://www.freshports.org/devel/libinotify/ (libinotify-20180201_2)
Worked with 1.9.0

**Comment by whyman** [comment]
Thanks for letting us know.

Not sure how this happened as I thought we had this combination in our CI/CD.

**Comment by diizzyy** [comment]
It's not enabled according to https://github.com/gerbera/gerbera/blob/master/.builds/freebsd.yml#L29 and libinotify is missing as package

**Comment by whyman** [comment]
Ah yep, good spot. We should add that.

**Comment by diizzyy** [comment]
@whyman
Not sure if it makes sense to switch to libnpupnp while at it, that's what I use as default for the port uses at least.
https://www.freshports.org/net/gerbera/

**Comment by whyman** [comment]
I don't consider npupnp officially supported, at least I only ever test against libupnp 😅. I am sure it works well though!

**Comment by neheb** [comment]
Is that just a missing header?

**Comment by neheb** [comment]
Yeah it is. Just need to include sstream.
