### ISSUE TITLE
Gerbera v1.4.0  fail to build with pupnp v1.12.0

### ISSUE THREAD

**Issue by uzhinskiy** [gerbera/gerbera#751]
Hi,
On Debian 10 i386:
Compiled and installed pupnp v1.12.0

`cmake ../gerbera -DWITH_MAGIC=1 -DWITH_MYSQL=1 -DWITH_CURL=1 -DWITH_JS=1 -DWITH_TAGLIB=1 -DWITH_AVCODEC=1 -DWITH_FFMPEGTHUMBNAILER=1 -DWITH_EXIF=1 -DWITH_EXIV2=1 -DWITH_SYSTEMD=1 -DWITH_DEBUG=1 -DWITH_PROTOCOL_EXTENSIONS=1`

-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
....
-- Found UPnP: /usr/local/lib/libupnp.so (found version "1.12.0")
....

`make -j4`
`In file included from /root/gerbera/src/server.h:38,
                 from /root/gerbera/src/atrailers_service.cc:39:
/root/gerbera/src/request_handler.h:41:26: error: ‘IN’ has not been declared
     virtual void getInfo(IN const char *filename, OUT UpnpFileInfo *info) = 0;`

Full build-log - in attached file
[gerbera_build.log](https://github.com/gerbera/gerbera/files/4365027/gerbera_build.log)

**Comment by pamapa** [comment]
IN+OUT have been removed after 1.4.0 release see here: https://github.com/gerbera/gerbera/commit/a4870cbdbcbbd835b10ea6f464c981f01da0b542

Do you get the same error with master? We can not fix anyway a tagged version.

**Comment by uzhinskiy** [comment]
With master-branch I have the following errors:
[ 97%] Linking CXX static library liblibgerbera.a
[ 97%] Built target libgerbera
Scanning dependencies of target gerbera
[ 98%] Building CXX object CMakeFiles/gerbera.dir/src/main.cc.o
[100%] Linking CXX executable gerbera
/usr/bin/ld: liblibgerbera.a(upnp_headers.cc.o): in function `Headers::writeHeaders(s_UpnpFileInfo*) const':
upnp_headers.cc:(.text+0x714): undefined reference to `UpnpListEnd(UpnpListHead*)'
/usr/bin/ld: upnp_headers.cc:(.text+0x726): undefined reference to `UpnpListInsert(UpnpListHead*, UpnpListHead*, UpnpListHead*)'
/usr/bin/ld: liblibgerbera.a(upnp_headers.cc.o): in function `Headers::readHeaders[abi:cxx11](s_UpnpFileInfo*)':
upnp_headers.cc:(.text+0x7e3): undefined reference to `UpnpListBegin(UpnpListHead*)'
/usr/bin/ld: upnp_headers.cc:(.text+0x7f6): undefined reference to `UpnpListEnd(UpnpListHead*)'
/usr/bin/ld: upnp_headers.cc:(.text+0x8ba): undefined reference to `UpnpListNext(UpnpListHead*, UpnpListHead*)'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/gerbera.dir/build.make:101: gerbera] Ошибка 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/gerbera.dir/all] Ошибка 2
make: *** [Makefile:130: all] Ошибка 2

**Comment by stefan-langenmaier** [comment]
Just had the same issue on Gentoo with libupnp 1.12 as dependency. I reverted to libupnp 1.6.21 for which it is working at the moment.

**Comment by uzhinskiy** [comment]
This [#682](https://github.com/gerbera/gerbera/issues/682) - helped to me. Compiling is done without errors. But "custom-http-header" still not work :
`info: (NOT) Adding HTTP header "transferMode.dlna.org: Streaming"`

**Comment by pamapa** [comment]
see https://github.com/pupnp/pupnp/commit/5a8e93f1a57cce5cead5c8c566a75f7c7c294c97

For now use the pupnp version 1.12.0 + patch. You can use scripts/install-pupnp.sh this applies the needed fix before compiling and installing

**Comment by uzhinskiy** [comment]
Patch for pupnp - helped.
